### ISSUE TITLE
2016 General Election Precinct-Level Down-Ballot Races

### ISSUE THREAD

**Issue by chrisroat** [openelections/openelections-data-ca#110]
Add results of US House and State-level races.

@joemfox @charles-difazio How were the 2016 general precinct-level files generated?  I see src/parse_general_2016.py which does just counties, and src/swdb/parse.py which doesn't have 'G16'.

**Comment by charles-difazio** [comment]
@joemfox imported the results for President, Senate, and Ballot Measures from https://github.com/datadesk/california-2016-election-precinct-maps

I have a local branch adding the downballot 2016 results, so hopefully you haven't started work on this yet. I'll send a pull request out tonight for those after I do a quick verification.

**Comment by charles-difazio** [comment]
Adding a list here for counties we have so far:

- [X] Alameda
- [ ] Alpine
- [X] Amador
- [X] Butte
- [X] Calaveras
- [X] Colusa
- [X] Contra Costa
- [X] Del Norte
- [X] El Dorado
- [X] Fresno
- [X] Glenn
- [X] Humboldt
- [ ] Imperial
- [X] Inyo
- [X] Kern
- [X] Kings
- [X] Lake
- [X] Lassen
- [X] Los Angeles
- [X] Madera
- [X] Marin
- [X] Mariposa
- [X] Mendocino
- [X] Merced
- [X] Modoc
- [X] Mono
- [X] Monterey
- [X] Napa
- [X] Nevada
- [X] Orange
- [X] Placer
- [X] Plumas
- [X] Riverside
- [X] Sacramento
- [X] San Benito
- [X] San Bernardino
- [X] San Diego
- [X] San Francisco
- [X] San Joaquin
- [X] San Luis Obispo
- [X] San Mateo
- [X] Santa Barbara
- [X] Santa Clara
- [X] Santa Cruz
- [X] Shasta
- [X] Sierra
- [X] Siskiyou
- [X] Solano
- [X] Sonoma
- [X] Stanislaus
- [X] Sutter
- [X] Tehama
- [X] Trinity
- [X] Tulare
- [X] Tuolumne
- [X] Ventura
- [X] Yolo
- [X] Yuba

**Comment by charles-difazio** [comment]
@chrisroat, that just leaves Alpine and Imperial counties, which haven't been processed for the Statewide Database yet. Depending on your timeframe and coverage needs, you may want to process them independently.

Alpine county has a [PDF](http://www.alpinecountyca.gov/DocumentCenter/View/1734), but it's at least text, so you should be able to pull it out using Tabula rather than needing to OCR.

Imperial county has both [PDF](http://www.co.imperial.ca.us/regvoters/index.asp?fileinc=Results11-8-16PDF) and [XLS](http://www.co.imperial.ca.us/regvoters/index.asp?fileinc=Results11-8-16XLS), but neither is consolidated, so you'd need to process each office's file.

**Comment by chrisroat** [comment]
Thanks so much for the PR and putting this data together.  My coverage needs for those counties are not immediate.  I suggest we defer until the Statewide DB is updated, and then re-run your scripts.

**Comment by lephead** [comment]
Here is my 2016 California.  The main difference between county canvasses and the statewide database is that the counties may cover up the vote in small precincts, while the statewide database has the vote listed.  I also have included write-in for president info as much as I could find, some counties had an overall total, and others I did the votes for Sanders and McMullin.
[1-2016CALIFORNIASTATEWIDE.xlsx](https://github.com/openelections/openelections-data-ca/files/1159650/1-2016CALIFORNIASTATEWIDE.xlsx)
